version: '3'

vars:
  WEB_DIR: packages/web
  API_DIR: packages/api

tasks:
  default:
    desc: Run both web app and API concurrently
    deps: [web, api]

  web:
    desc: Run the Dioxus web app on port 9000
    dir: "{{.WEB_DIR}}"
    cmds:
      - dx serve --port 9000
    env:
      DX_ENVIRONMENT: development

  api:setup:
    desc: Install worker-build if not available
    cmds:
      - |
        if ! command -v worker-build &> /dev/null; then
          echo "Installing worker-build..."
          cargo install worker-build --locked
        else
          echo "worker-build is already installed"
        fi

  api:
    desc: Run the Cloudflare Workers API on port 8000
    deps: [api:setup]
    dir: "{{.API_DIR}}"
    cmds:
      - wrangler dev --port 8000

  web:build:
    desc: Build the web app for production
    dir: "{{.WEB_DIR}}"
    cmds:
      - dx bundle --release --web

  api:build:
    desc: Build the API Worker
    dir: "{{.API_DIR}}"
    deps: [api:setup]
    cmds:
      - worker-build

  dev:pages:
    desc: Test Pages with Worker locally (builds both, then runs Pages dev)
    deps: [web:build, api:build]
    cmds:
      - |
        echo "ðŸš€ Testing Pages with Worker locally"
        echo ""
        echo "ðŸ“¦ Both web and API are built"
        echo ""
        echo "ðŸ”§ Starting Pages dev server with Worker..."
        echo "Note: This will serve static assets from target/dx/web/release/web/public"
        echo "      and run the API Worker to handle /api/* routes"
        echo ""
        wrangler pages dev target/dx/web/release/web/public \
          --compatibility-date=2024-01-01 \
          --local \
          --port=8788 \
          --worker-path=packages/api/build/index.js \
          --binding=DB:applymonitor-db

  deploy:test:
    desc: Test deploy both API Worker and web to the same Pages project
    deps: [web:build, api:build]
    cmds:
      - task: deploy:test:build-api
      - task: deploy:test:deploy-pages
      - task: deploy:test:deploy-api

  deploy:test:build-api:
    desc: Build API Worker
    dir: "{{.API_DIR}}"
    internal: true
    cmds:
      - worker-build

  deploy:test:deploy-pages:
    desc: Deploy Pages
    internal: true
    cmds:
      - |
        echo "ðŸš€ Testing deployment of API Worker + Web to same Pages project"
        echo ""
        echo "ðŸ“¦ Web assets already built in target/dx/web/release/web/public"
        echo ""
        echo "ðŸ”§ Step 1: Deploying static assets to Cloudflare Pages..."
        wrangler pages deploy target/dx/web/release/web/public \
          --project-name=applymonitor-web-production
        echo ""

  deploy:test:deploy-api:
    desc: Deploy API Worker
    dir: "{{.API_DIR}}"
    internal: true
    cmds:
      - |
        echo ""
        echo "ðŸ”§ Step 2: Deploying API Worker..."
        echo "Note: After deploying, attach the Worker to the Pages project via:"
        echo "  - Cloudflare Dashboard: Pages > applymonitor-web-production > Settings > Functions"
        echo "  - Or use the Pages API to attach the Worker programmatically"
        echo ""
        wrangler deploy --env production
        echo ""
        echo "âœ… Deployment complete!"

  api:migrate:
    desc: Apply database migrations locally
    dir: "{{.API_DIR}}"
    cmds:
      - wrangler d1 migrations apply DB --local

  api:migrate:prod:
    desc: Apply database migrations to production
    dir: "{{.API_DIR}}"
    cmds:
      - wrangler d1 migrations apply DB --remote

  setup:
    desc: Set up Cloudflare resources (D1 database, Pages project, Worker, Custom domain)
    cmds:
      - task: setup:d1
      - task: setup:pages
      - task: setup:domain
      - task: setup:verify

  setup:d1:
    desc: Create D1 database if it doesn't exist
    dir: "{{.API_DIR}}"
    cmds:
      - |
        echo "Creating D1 database: applymonitor-db"
        wrangler d1 create applymonitor-db || echo "Database may already exist"
        echo "âœ… Done! Update wrangler.toml with the database_id from the output above"

  setup:pages:
    desc: Create Cloudflare Pages project if it doesn't exist
    cmds:
      - |
        echo "Checking for Cloudflare Pages project: applymonitor-web-production"
        if wrangler pages project list --json 2>/dev/null | jq -e '.[] | select(.name == "applymonitor-web-production")' >/dev/null; then
          echo "âœ… Cloudflare Pages project 'applymonitor-web-production' already exists"
        else
          echo "Creating Cloudflare Pages project: applymonitor-web-production"
          wrangler pages project create applymonitor-web-production --production-branch=main
          echo "âœ… Created Cloudflare Pages project"
        fi
        echo ""
        echo "ðŸ“ To add custom domain 'applymonitor.com' to Pages:"
        echo "   Go to Cloudflare Dashboard > Pages > applymonitor-web-production > Custom domains"
        echo "   Or run: wrangler pages domain add applymonitor.com --project-name=applymonitor-web-production"

  setup:domain:
    desc: Add custom domain applymonitor.com to Pages and Worker
    cmds:
      - |
        echo "ðŸŒ Setting up custom domain: applymonitor.com"
        echo ""
        echo "ðŸ“„ Adding domain to Pages project..."
        echo "Note: Custom domains for Pages must be added via Cloudflare Dashboard:"
        echo "      Pages > applymonitor-web-production > Custom domains > Set up a custom domain"
        echo ""
        echo "ðŸ“„ Adding domain to Worker..."
        echo "Note: Worker routes are configured in wrangler.toml"
        echo "      Custom domain should be added via Cloudflare Dashboard:"
        echo "      Workers & Pages > applymonitor-api-production > Triggers > Custom Domains"
        echo ""
        echo "âœ… Domain setup instructions provided"

  setup:verify:
    desc: Verify all Cloudflare resources are set up
    cmds:
      - |
        echo ""
        echo "ðŸ” Verifying Cloudflare resources..."
        echo ""
        echo "D1 Databases:"
        wrangler d1 list --json | jq -r '.[] | "  âœ… \(.name) (ID: \(.uuid))"'
        echo ""
        echo "Pages Projects:"
        wrangler pages project list --json 2>/dev/null | jq -r '.[] | "  âœ… \(.name)"'
        echo ""
        echo "âœ… Setup verification complete"

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
