version: '3'

includes:
  run: ./tasks/run.yml
  build: ./tasks/build.yml
  deploy: ./tasks/deploy.yml
  test: ./tasks/test.yml
  quality: ./tasks/quality.yml
  setup: ./tasks/setup.yml

vars:
  WEB_DIR: packages/web
  API_DIR: packages/api

tasks:
  default:
    desc: Run both web app and API concurrently
    deps: [run:web, run:api]
